# Generated by Django 5.0.4 on 2024-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kozel", "0014_carrito_compra_tipoarticulo_articulo_variedad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variedad",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
