# Generated by Django 5.0.4 on 2024-08-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kozel", "0015_variedad_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="producto_mes",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
