# Generated by Django 5.0.4 on 2024-09-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kozel", "0017_carritovariedad_cantidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="curso",
        ),
        migrations.DeleteModel(
            name="Asignatura",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Estudiante",
        ),
    ]
